### ISSUE TITLE
Time restriction

### ISSUE THREAD

**Issue by Jakeii** [tunapanda/funzo-app#34]
restrict the duration that access to the book is granted.

probably using a decryption key that expires?

> * If the IP address shows a US/Canada location, then the student must enter a unique code proving they are "in an educational setting" ­ **that code determines the length of time the student will be able to access the eBook**.
> * If the IP address shows a non­US/Canada location, then the learner can download the eBook which is "charged" (the equivalent of "borrowed from the library" in the US context) for a **certain period of time**.

**Comment by usernamenumber** [comment]
This has been implemented. See https://github.com/tunapanda/funzo-app/blob/3bab743522d2496ffd955e9c8f9062624760353d/app/pods/section/model.js

IMO the only reason to keep this open is because the current solution only supports fixed expiration dates, whereas future versions will need to support "refilling" an expiration counter. But that will probably require a completely new implementation so I'd say it should get its own issue. 

@Jakeii, close if you agree.

**Comment by usernamenumber** [comment]
Closing this. We can create a new issue when it's time to implement a re-fillable solution.
